package com.tweet.data;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="TweetData")
public class TweetData {

	private String id;
	private long entryDate = new Date().getTime();
	private String tweet_text;
	private String tweet_user;
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName="entry_date")
	public long getEntryDate() {
		return entryDate;
	}
	public void setEntryDate(long entryDate) {
		this.entryDate = entryDate;
	}
	
	@DynamoDBAttribute(attributeName="tweet_text")
	public String getTweet_text() {
		return tweet_text;
	}
	public void setTweet_text(String tweet_text) {
		this.tweet_text = tweet_text;
	}
	
	@DynamoDBAttribute(attributeName="tweet_user")
	public String getTweet_user() {
		return tweet_user;
	}
	public void setTweet_user(String tweet_user) {
		this.tweet_user = tweet_user;
	}
	
	
	
	
}
